name: sociallogin
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  flutter_auth_buttons: ^0.5.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Bold.ttf
        - asset: fonts/DancingScript-Medium.ttf
        - asset: fonts/DancingScript-Regular.ttf
        - asset: fonts/DancingScript-SemiBold.ttf
